apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: techbiits-com-tls
spec:
  secretName: techbiits-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: techbiits.com
  dnsNames:
    - techbiits.com
    - www.techbiits.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - techbiits.com
          - www.techbiits.com